### ISSUE TITLE
Review Code of Conduct

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/bangalore#2]
We've provided a draft Code of Conduct for you that includes the contact information you provided for reporting purposes. Please ensure that these contact details are correct.

Please ensure that all chapter organizers have reviewed the CoC thoroughly and are comfortable enforcing it.

(This will need to be done before we can list your chapter on our website.)

**Comment by terichadbourne** [comment]
@kishansagathiya  Just checking in to confirm you've reviewed your chapter's CoC and are comfortable with it. If so, please go ahead and close out this issue. Thanks!

**Comment by kishansagathiya** [comment]
@terichadbourne 
Sorry about the delay, I had some problem creating the meetup group. That's why was delaying this.
I have gone through code of conduct. Looks good to me.
