### ISSUE TITLE
Add chapter to our listings

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/bangalore#3]
Once issues #1 & #2 are complete, please complete Step 5 in the [chapter setup instructions](https://github.com/ProtoSchool/organizing#how-to-start-a-new-protoschool-chapter) by opening a pull request to have your chapter included in the [list of ProtoSchool chapters](https://proto.school/#/chapters).

Please be sure to include the `repo` field so that your listing will link to this chapter repo. Should you decide that you'd like your listing to go to a website instead (now or in the future), you can add an additional `website` field with the appropriate URL, which will update the link.

**Comment by terichadbourne** [comment]
@kishansagathiya Just a quick reminder that the Bangalore chapter is not yet listed on our website. If you're done prepping your repo and are ready for that to happen, please go ahead and follow the appropriate steps (see link above) to open a PR for that addition. Thanks!

**Comment by kishansagathiya** [comment]
Sorry about the delay, https://github.com/ProtoSchool/protoschool.github.io/pull/166

**Comment by terichadbourne** [comment]
🎉
